server:
  port: 8847  
    
swagger:
  application:
    description: Product Manegement Service
    version: 1.0
    contact:
      name: Chinthana
      email: chinthana.thennakoon@axiatadigitallabs.com
      url:

spring:
  application:
    name: product-management-service
  jpa:
    hibernate: 
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  mvc:
    pathmatch:      matching-strategy: ANT_PATH_MATCHER                
  h2:
    console:
      enabled: true
      path: /h2-console 
      settings:        web-allow-others: true     
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: -1
      enabled: true
      
  datasource:
     driverClassName: org.h2.Driver
     url: jdbc:h2:mem:testdb
     username: sa
     password:
  
#  datasource:
#      url: jdbc:postgresql://localhost:5434/testdb
#      username: postgres
#      password: root
    

