server:
  port: 8847  
    
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
 
logging:
  level:
    org: 
      hibernate:
        SQL: DEBUG

spring:
  application:
    name: product-manegement-service
  jpa:
    hibernate: 
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true     
  h2:
    console:
      enabled: true
      path: /h2-console      
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: -1
      enabled: true
      
#  datasource:
#     driverClassName: org.h2.Driver
#     url: jdbc:h2:mem:testdb
#     username: sa
#     password:
  
  datasource:
      url: jdbc:postgresql://localhost:5434/testdb
      username: postgres
      password: root
    

